skillsort/config/routes.rb
Skillsort::Application.routes.draw do


  root 'main#index'


  # API
  namespace :api do
    resources :skills, only: :index
    resources :axes, only: :index
  end


  # Admin
  namespace :admin do
    resources :industries
    resources :functions
    resources :countries
    resources :axes
    resources :skills
    resources :games


    get "download-all-games" => "games#download_all", as: :download_all_games
    get "games/:id/download" => "games#download", as: :download_game
  end


  # Main
  get "main/index"
  get "login" => "main#index"
  get "about" => "main#about"
  get "about_us" => "main#about_us"
  get "privacy-terms" => "main#privacy_terms"
  get "feedback" => "main#feedback"
  post "feedback-submit" => "main#feedback_submit"


  # Skillsort
  get 'try-game', to: 'skillsort#try_game'
  get "play-game/:game_type" => 'skillsort#play_game'
  get "job-information" => "skillsort#job_information", as: :job_information
  post "job-information-submit" => "skillsort#job_information_submit", as: :job_information_submit
  get "dashboard" => "skillsort#dashboard", as: :dashboard
  post "submit-game" => "skillsort#submit_game"


  # devise_for :users
  devise_scope :user do
    post "/register" => "account#create", as: :user_registration
  end
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
end

skillsort/app/models/country.rb
class Country < ActiveRecord::Base
  scope :active, -> { where( active: true ) }
end

skillsort/app/controllers/admin/countries_controller.rb
module Admin
  class CountriesController < Admin::AdminController
    before_action :set_country, only: [:show, :edit, :update, :destroy]


    # GET /countries
    # GET /countries.json
    def index
      @countries = Country.all
    end


    # GET /countries/1
    # GET /countries/1.json
    def show
    end


    # GET /countries/new
    def new
      @country = Country.new
    end


    # GET /countries/1/edit
    def edit; end


    # POST /countries
    # POST /countries.json
    def create
      @country = Country.new(country_params)

      respond_to do |format|
        if @country.save
          format.html { redirect_to @country, notice: 'Country was successfully created.' }
          format.json { render action: 'show', status: :created, location: @country }
        else
          format.html { render action: 'new' }
          format.json { render json: @country.errors, status: :unprocessable_entity }
        end
      end
    end


    # PATCH/PUT /countries/1
    # PATCH/PUT /countries/1.json
    def update
      respond_to do |format|
        if @country.update(country_params)
          format.html { redirect_to @country, notice: 'Country was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @country.errors, status: :unprocessable_entity }
        end
      end
    end


    # DELETE /countries/1
    # DELETE /countries/1.json
    def destroy
      @country.destroy
      respond_to do |format|
        format.html { redirect_to admin_countries_url }
        format.json { head :no_content }
      end
    end


    private


    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :active)
    end
  end
end

skillsort/app/views/admin/countries/_form.html.erb
<%= form_for(@country, url: admin_country_path(@country)) do |f| %>
  <% if @country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% @country.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

skillsort/app/views/admin/countries/edit.html.erb
<h1>Editing country</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_country_path(@country) %> |
<%= link_to 'Back', admin_countries_path %>

skillsort/app/views/admin/countries/index.html.erb
<h1>Listing countries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.active %></td>
        <td><%= link_to 'Show', admin_country_path(country) %></td>
        <td><%= link_to 'Edit', edit_admin_country_path(country) %></td>
        <td><%= link_to 'Destroy', admin_country_path(country), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Country', new_admin_country_path %>

skillsort/app/views/admin/countries/new.html.erb
<h1>New country</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_countries_path %>

skillsort/app/views/admin/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @country.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @country.active %>
</p>

<%= link_to 'Edit', edit_admin_country_path(@country) %> |
<%= link_to 'Back', admin_countries_path %>