skillsort/config/routes.rb
Skillsort::Application.routes.draw do


  root 'main#index'


  # API
  namespace :api do
    resources :skills, only: :index
    resources :axes, only: :index
  end


  # Admin
  namespace :admin do
    resources :industries
    resources :functions
    resources :countries
    resources :axes
    resources :skills
    resources :games


    get "download-all-games" => "games#download_all", as: :download_all_games
    get "games/:id/download" => "games#download", as: :download_game
  end


  # Main
  get "main/index"
  get "login" => "main#index"
  get "about" => "main#about"
  get "about_us" => "main#about_us"
  get "privacy-terms" => "main#privacy_terms"
  get "feedback" => "main#feedback"
  post "feedback-submit" => "main#feedback_submit"


  # Skillsort
  get 'try-game', to: 'skillsort#try_game'
  get "play-game/:game_type" => 'skillsort#play_game'
  get "job-information" => "skillsort#job_information", as: :job_information
  post "job-information-submit" => "skillsort#job_information_submit", as: :job_information_submit
  get "dashboard" => "skillsort#dashboard", as: :dashboard
  post "submit-game" => "skillsort#submit_game"


  # devise_for :users
  devise_scope :user do
    post "/register" => "account#create", as: :user_registration
  end
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
end

skillsort/app/models/game.rb
require 'csv'

class Game < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :user
	validates_presence_of :version
	validates_presence_of :result
	validates_presence_of :game_type


	def skills_for (options={})
		game_type = options[:game_type]
		value = options[:value]

		hash = Array.new
		self.result_hash.each { |k, v|
			skill = Skill.find(k)
			axis = Axis.where({game_type: 1, value: v}).first
			hash << skill if axis.value == value
		}
		hash
	end


	# This method writes a CSV file of one game result
	def populateResult!
		filename = 'game_result.csv'
		file = File.new(Rails.public_path.to_s+"/#{filename}", 'w')
		begin	
			self.result_hash.each { |k, v|
				skill = Skill.find(k)
				axis = Axis.find(v)
				file.puts "#{k},\"#{skill.name}\",#{axis.name}"
			}
			file.close
		rescue Exception => e
			STDERR.puts "Error with file write: #{e}"
			file.close
		end
	end


	# This method write a CSV file of all game results
	def self.allResults!

		filename = 'game_all_results.csv'
		file = File.new(Rails.public_path.to_s+"/#{filename}", 'w')

		begin
			# Print file headers
			header = "id,"
			(1..49).each { |i| header += "#{i},"}
			header += "50"
			file.puts "#{header}"

			# Get all games, for each game, print user and value
			self.all.each { |g|

				result = g.user_id.to_s + ","

				g.result_hash.each { |k,v|
					# skill = Skill.find(k)
					axis = Axis.find(v)
					result += "#{axis.value},"
				}

				file.puts result
			}
			file.close
		rescue Exception => e
			STDERR.puts "Error with file write: #{e}"
			file.close
		end
	end


	def result_hash
		result_hash = Hash.new
		self.result.split(';').each do |pair|
			split_pair = pair.split(',')
			result_hash[split_pair[0].to_i] = split_pair[1].to_i
		end
		result_hash
	end
end

skillsort/app/controllers/admin/games_controller.rb
module Admin
  class GamesController < Admin::AdminController
    before_action :set_game, only: [:show, :edit, :update, :destroy]


    # GET /games
    # GET /games.json
    def index
      @games = Game.all
    end


    # GET /games/1
    # GET /games/1.json
    def show; end


    # Sends a CSV formated report of a game to client
    def download
      Game.find(params[:id]).populateResult!
      @filename = Rails.public_path.to_s+'/game_result.csv'
      send_file(@filename, :filename => "game_result.csv")
    end


    # Sends a CSV formated report of all games to client
    def download_all
      Game.allResults!
      @filename = Rails.public_path.to_s+'/game_all_results.csv'
      send_file(@filename, :filename => "game_all_results.csv")
    end


    # GET /games/new
    def new
      @game = Game.new
    end


    # GET /games/1/edit
    def edit; end


    # POST /games
    # POST /games.json
    def create
      @game = Game.new(game_params)

      respond_to do |format|
        if @game.save
          format.html { redirect_to @game, notice: 'Game was successfully created.' }
          format.json { render action: 'show', status: :created, location: @game }
        else
          format.html { render action: 'new' }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    end


    # PATCH/PUT /games/1
    # PATCH/PUT /games/1.json
    def update
      respond_to do |format|
        if @game.update(game_params)
          format.html { redirect_to @game, notice: 'Game was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    end


    # DELETE /games/1
    # DELETE /games/1.json
    def destroy
      @game.destroy
      respond_to do |format|
        format.html { redirect_to admin_games_url }
        format.json { head :no_content }
      end
    end


    private


    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end


    # Only allow the white list through.
    def game_params
      params.require(:game).permit(:user_id, :version, :game_type, :result)
    end
  end
end

skillsort/app/views/admin/games/_form.html.erb
<%= form_for(@game, url: admin_game_path(@game)) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :version %><br>
    <%= f.text_field :version %>
  </div>
  <div class="field">
    <%= f.label :game_type %><br>
    <%= f.text_area :game_type %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_area :result %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

skillsort/app/views/admin/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_game_path(@game) %> |
<%= link_to 'Back', admin_games_path %>

skillsort/app/views/admin/games/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

      <h1>Listing games</h1>

      <table class="table table-striped table-hover table-responsive">
        <thead>
          <tr>
            <th>User</th>
            <th>Version</th>
            <th>Game Type</th>
            <th>Result</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @games.each do |game| %>
            <tr>
              <td><%= game.user_id %></td>
              <td><%= game.version %></td>
              <td><%= game.game_type %></td>
              <td><%= game.result.truncate(50) if game.result != nil %></td>
              <td><%= link_to 'Show', admin_game_path(game) %></td>
              <td><%= link_to 'Download', admin_download_game_path(game) %></td>
              <td><%= link_to 'Edit', edit_admin_game_path(game) %></td>
              <td><%= link_to 'Destroy', admin_game_path(game), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <a href="/download-all" class="btn btn-success">Download All</a>

    </div>
  </div>
</div>

skillsort/app/views/admin/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

skillsort/app/views/admin/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @game.user_id %>
</p>

<p>
  <strong>Version:</strong>
  <%= @game.version %>
</p>

<p>
  <strong>Game Type:</strong>
  <%= @game.game_type %>
</p>

<p>
  <strong>Result:</strong>
  <%= @game.result_hash %>
</p>

<%= link_to 'Edit', edit_admin_game_path(@game) %> |
<%= link_to 'Back', admin_games_path %>