skillsort/config/routes.rb
Skillsort::Application.routes.draw do


  root 'main#index'


  # API
  namespace :api do
    resources :skills, only: :index
    resources :axes, only: :index
  end


  # Admin
  namespace :admin do
    resources :industries
    resources :functions
    resources :countries
    resources :axes
    resources :skills
    resources :games


    get "download-all-games" => "games#download_all", as: :download_all_games
    get "games/:id/download" => "games#download", as: :download_game
  end


  # Main
  get "main/index"
  get "login" => "main#index"
  get "about" => "main#about"
  get "about_us" => "main#about_us"
  get "privacy-terms" => "main#privacy_terms"
  get "feedback" => "main#feedback"
  post "feedback-submit" => "main#feedback_submit"


  # Skillsort
  get 'try-game', to: 'skillsort#try_game'
  get "play-game/:game_type" => 'skillsort#play_game'
  get "job-information" => "skillsort#job_information", as: :job_information
  post "job-information-submit" => "skillsort#job_information_submit", as: :job_information_submit
  get "dashboard" => "skillsort#dashboard", as: :dashboard
  post "submit-game" => "skillsort#submit_game"


  # devise_for :users
  devise_scope :user do
    post "/register" => "account#create", as: :user_registration
  end
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
end

skillsort/app/models/skill.rb
class Skill < ActiveRecord::Base
  scope :active, -> { where( active: true ) }
end

skillsort/app/controllers/admin/skills_controller.rb
module Admin
  class SkillsController < Admin::AdminController
    before_action :set_skill, only: [:show, :edit, :update, :destroy]


    def skillsort_skills
      @skills = Skill.active
      render json: @skills
    end


    # GET /skills
    # GET /skills.json
    def index
      @skills = Skill.all
    end


    # GET /skills/1
    # GET /skills/1.json
    def show; end


    # GET /skills/new
    def new
      @skill = Skill.new
    end


    # GET /skills/1/edit
    def edit; end


    # POST /skills
    # POST /skills.json
    def create
      @skill = Skill.new(skill_params)

      respond_to do |format|
        if @skill.save
          format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
          format.json { render action: 'show', status: :created, location: @skill }
        else
          format.html { render action: 'new' }
          format.json { render json: @skill.errors, status: :unprocessable_entity }
        end
      end
    end


    # PATCH/PUT /skills/1
    # PATCH/PUT /skills/1.json
    def update
      respond_to do |format|
        if @skill.update(skill_params)
          format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @skill.errors, status: :unprocessable_entity }
        end
      end
    end


    # DELETE /skills/1
    # DELETE /skills/1.json
    def destroy
      @skill.destroy
      respond_to do |format|
        format.html { redirect_to admin_skills_url }
        format.json { head :no_content }
      end
    end


    private


    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:name, :description, :active)
    end
  end
end

skillsort/app/controllers/api/skills_controller.rb
module Api
  class SkillsController < ApplicationController


    def index
      @skills = Skill.active.select( 'id, name, description' )
      render json: @skills, status: 200
    end
  end
end

skillsort/app/views/admin/skills/_form.html.erb
<%= form_for(@skill, url: admin_skill_path(@skill)) do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

skillsort/app/views/admin/skills/edit.html.erb
<h1>Editing skill</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_skill_path(@skill) %> |
<%= link_to 'Back', admin_skills_path %>

skillsort/app/views/admin/skills/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <h1>Listing skills</h1>

      <table class="table table-striped table-hover table-responsive">
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Description</th>
            <th>Active</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @skills.each do |skill| %>
            <tr>
              <td><%= skill.id %></td>
              <td><%= skill.name %></td>
              <td><%= skill.description %></td>
              <td><%= skill.active %></td>
              <td><%= link_to 'Show', admin_skill_path(skill) %></td>
              <td><%= link_to 'Edit', edit_admin_skill_path(skill) %></td>
              <td><%= link_to 'Destroy', admin_skill_path(skill), method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br/>
      <%= link_to 'New Skill', new_admin_skill_path %>
      <br/><br/>

    </div>
  </div>
</div>

skillsort/app/views/admin/skills/new.html.erb
<h1>New skill</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_skills_path %>

skillsort/app/views/admin/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @skill.description %>
</p>

<p>
  <strong>Active:</strong>
  <%= @skill.active %>
</p>

<%= link_to 'Edit', edit_admin_skill_path(@skill) %> |
<%= link_to 'Back', admin_skills_path %>