skillsort/config/routes.rb
Skillsort::Application.routes.draw do


  root 'main#index'


  # API
  namespace :api do
    resources :skills, only: :index
    resources :axes, only: :index
  end


  # Admin
  namespace :admin do
    resources :industries
    resources :functions
    resources :countries
    resources :axes
    resources :skills
    resources :games


    get "download-all-games" => "games#download_all", as: :download_all_games
    get "games/:id/download" => "games#download", as: :download_game
  end


  # Main
  get "main/index"
  get "login" => "main#index"
  get "about" => "main#about"
  get "about_us" => "main#about_us"
  get "privacy-terms" => "main#privacy_terms"
  get "feedback" => "main#feedback"
  post "feedback-submit" => "main#feedback_submit"


  # Skillsort
  get 'try-game', to: 'skillsort#try_game'
  get "play-game/:game_type" => 'skillsort#play_game'
  get "job-information" => "skillsort#job_information", as: :job_information
  post "job-information-submit" => "skillsort#job_information_submit", as: :job_information_submit
  get "dashboard" => "skillsort#dashboard", as: :dashboard
  post "submit-game" => "skillsort#submit_game"


  # devise_for :users
  devise_scope :user do
    post "/register" => "account#create", as: :user_registration
  end
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
end

skillsort/app/models/industry.rb
class Industry < ActiveRecord::Base
	scope :active, -> { where(active: true) }
end

skillsort/app/controllers/admin/industries_controller.rb
module Admin
  class IndustriesController < Admin::AdminController
    before_action :set_industry, only: [:show, :edit, :update, :destroy]


    # GET /industries
    # GET /industries.json
    def index
      @industries = Industry.all
    end


    # GET /industries/1
    # GET /industries/1.json
    def show; end


    # GET /industries/new
    def new
      @industry = Industry.new
    end


    # GET /industries/1/edit
    def edit; end


    # POST /industries
    # POST /industries.json
    def create
      @industry = Industry.new(industry_params)

      respond_to do |format|
        if @industry.save
          format.html { redirect_to @industry, notice: 'Industry was successfully created.' }
          format.json { render action: 'show', status: :created, location: @industry }
        else
          format.html { render action: 'new' }
          format.json { render json: @industry.errors, status: :unprocessable_entity }
        end
      end
    end


    # PATCH/PUT /industries/1
    # PATCH/PUT /industries/1.json
    def update
      respond_to do |format|
        if @industry.update(industry_params)
          format.html { redirect_to @industry, notice: 'Industry was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @industry.errors, status: :unprocessable_entity }
        end
      end
    end


    # DELETE /industries/1
    # DELETE /industries/1.json
    def destroy
      @industry.destroy
      respond_to do |format|
        format.html { redirect_to admin_industries_url }
        format.json { head :no_content }
      end
    end


    private


    # Use callbacks to share common setup or constraints between actions.
    def set_industry
      @industry = Industry.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def industry_params
      params.require(:industry).permit(:name, :active)
    end
  end
end

skillsort/app/views/admin/industries/_form.html.erb
<%= form_for(@industry, url: admin_industry_path(@industry)) do |f| %>
  <% if @industry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@industry.errors.count, "error") %> prohibited this industry from being saved:</h2>

      <ul>
      <% @industry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

skillsort/app/views/admin/industries/edit.html.erb
<h1>Editing industry</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_industry_path(@industry) %> |
<%= link_to 'Back', admin_industries_path %>

skillsort/app/views/admin/industries/index.html.erb
<div class="row">
<h1>Listing industries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @industries.each do |industry| %>
      <tr>
        <td><%= industry.name %></td>
        <td><%= industry.active %></td>
        <td><%= link_to 'Show', admin_industry_path(industry) %></td>
        <td><%= link_to 'Edit', edit_admin_industry_path(industry) %></td>
        <td><%= link_to 'Destroy', admin_industry_path(industry), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Industry', new_admin_industry_path %>

</div>

skillsort/app/views/admin/industries/new.html.erb
<h1>New industry</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_industries_path %>

skillsort/app/views/admin/industries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @industry.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @industry.active %>
</p>

<%= link_to 'Edit', edit_admin_industry_path(@industry) %> |
<%= link_to 'Back', admin_industries_path %>